import { writeFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { generateAuthoringPlan } from "../../src/modules/authoring/index.js";

describe("authoring providers", () => {
  it("uses the deterministic parser by default", async () => {
    const result = await generateAuthoringPlan({
      prompt: "OpenRouter 走香港，每45分钟自动更新",
      provider: "deterministic",
    });

    expect(result.providerUsed).toBe("deterministic");
    expect(result.plan.scheduleIntervalMinutes).toBe(45);
    expect(result.plan.beforeBuiltins.some((rule) => rule.route === "HK")).toBe(true);
  });

  it("accepts exec-provider JSON plans", async () => {
    const result = await generateAuthoringPlan({
      prompt: "视频网站走新加坡",
      provider: "exec",
      execCommand: "fake-author",
      execArgs: ["{{prompt}}"],
      runner: async () => ({
        exitCode: 0,
        stdout: JSON.stringify({
          templateIds: ["video-sg"],
          notes: ["Generated by fake provider"],
        }),
        stderr: "",
        timedOut: false,
      }),
    });

    expect(result.providerUsed).toBe("exec");
    expect(result.plan.templateIds).toContain("video-sg");
    expect(result.plan.beforeBuiltins.some((rule) => rule.route === "SG")).toBe(true);
  });

  it("extracts exec-provider plans from fenced JSON output", async () => {
    const result = await generateAuthoringPlan({
      prompt: "OpenRouter 走香港",
      provider: "exec",
      execCommand: "fake-author",
      execArgs: ["{{full_prompt}}"],
      runner: async () => ({
        exitCode: 0,
        stdout: [
          "Here is your plan:",
          "```json",
          JSON.stringify({
            beforeBuiltins: [{ domainSuffix: "openrouter.ai", route: "AI-Out" }],
            notes: ["Generated from fenced output"],
          }),
          "```",
        ].join("\n"),
        stderr: "",
        timedOut: false,
      }),
    });

    expect(result.providerUsed).toBe("exec");
    expect(result.plan.beforeBuiltins.some((rule) => rule.route === "AI-Out")).toBe(true);
    expect(result.plan.notes).toContain("Generated from fenced output");
  });

  it("reads exec-provider plans from the configured output file", async () => {
    const result = await generateAuthoringPlan({
      prompt: "视频网站走新加坡，每45分钟自动更新",
      provider: "exec",
      execCommand: "fake-author",
      execArgs: ["--out", "{{output_file}}", "{{schema_file}}", "{{context_json}}"],
      runner: async ({ env }) => {
        const outputFile = env?.SINGBOX_IAC_AUTHOR_OUTPUT_FILE;
        const schemaFile = env?.SINGBOX_IAC_AUTHOR_SCHEMA_FILE;
        const contextJson = env?.SINGBOX_IAC_AUTHOR_CONTEXT;
        expect(outputFile).toBeTruthy();
        expect(schemaFile).toBeTruthy();
        expect(contextJson).toContain("AI-Out");
        if (!outputFile) {
          throw new Error("expected output file path for exec-provider test");
        }

        await writeFile(
          outputFile,
          JSON.stringify({
            templateIds: ["video-sg"],
            scheduleIntervalMinutes: 45,
          }),
          "utf8",
        );

        return {
          exitCode: 0,
          stdout: "wrote output file",
          stderr: "",
          timedOut: false,
        };
      },
    });

    expect(result.providerUsed).toBe("exec");
    expect(result.plan.templateIds).toContain("video-sg");
    expect(result.plan.scheduleIntervalMinutes).toBe(45);
    expect(result.plan.beforeBuiltins.some((rule) => rule.route === "SG")).toBe(true);
  });

  it("falls back to the deterministic parser when auto provider execution fails", async () => {
    const result = await generateAuthoringPlan({
      prompt: "OpenRouter 走香港",
      provider: "auto",
      execCommand: "fake-author",
      execArgs: ["{{prompt}}"],
      runner: async () => {
        throw new Error("fake provider unavailable");
      },
    });

    expect(result.providerUsed).toBe("deterministic");
    expect(
      result.plan.notes.some((note) =>
        note.includes("Auto authoring fell back from exec to the deterministic parser"),
      ),
    ).toBe(true);
  });
});
